# -*- coding: utf-8 -*-
"""Da_day4(1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mvItgsM3CAn8cVybpSfe55bWb1w3hA_F
"""

#importing BeautifulSoup and Bs4
from bs4 import BeautifulSoup        #import libraries

#importing Rerqest
import requests

url = "https://www.kaggle.com/"      #save url

req = requests.get(url)      #request to access

a = BeautifulSoup(req.text,'html')        # access the Html code
print(a)